// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package query

import (
	"github.com/simonklee/sourdough/recipe"
)

type Ingredient struct {
	ID   int64
	Name string
	Kind recipe.Kind
}

type Recipe struct {
	ID   int64
	Name string
}

type RecipeIngredient struct {
	ID                 int64
	RecipeID           int64
	IngredientID       int64
	PreferUnitCategory recipe.UnitCategory
	Percentage         float64
	Dependency         string
}
