// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0

package query

import ()

type Ingredient struct {
	ID   int64
	Name string
}

type Recipe struct {
	ID   int64
	Name string
}

type RecipeIngredient struct {
	ID           int64
	RecipeID     int64
	IngredientID int64
	UnitType     string
	Percentage   float64
	Dependency   string
}
